$(document).ready(init);
console.log("working.");

var BOARD_SIZE = 10;
var ref = new Firebase("https://mywittlefirebase.firebaseio.com/");
var playersRef = ref.child("players");
var totalPlayers;
var myID;
var opponentID;

/**
 * When the page loads, we'll immediately calculate how many players are currently in
 * the game.
 */
playersRef.once('value', function(data) {
  totalPlayers = data.val() ? Object.keys(data.val()).length : 0;
  $('#currentPlayers').text(totalPlayers);
});

function init(){
  console.log("init fired.");
}

/**
 * When a user closes this tab in their browser, we'll delete their player object from
 * Firebase, that way someone else can join the game.
 */
window.onbeforeunload = function(event) {
  //playersRef.remove({?: id})
    };

/**
 * Creates a new 2D game board, with all tiles set to false.
 */
function createBoard() {
  var board = [];

  for (var i = 0; i < BOARD_SIZE; i++) {
    board.push(new Array(BOARD_SIZE));
    for (var j = 0; j < BOARD_SIZE; j++) {
      board[i][j] = false;
    }
  }

  return board;
}

$("button").on("click", addPlayer);

playersRef.on("value", function(snapshot) {
  totalPlayers = Object.keys(snapshot.val()).length;
  if (totalPlayers === 2 ) { //change this to if players are two AND (totalShips = 5) have been placed.
    //alert('Game is full, get out.');
    $('#currentPlayers').text(totalPlayers);
    console.log("There are two players. Prepare to enter.");
    countShips();
  }
}, function (errorObject) {
  console.log("The read failed: " + errorObject.code);
});


function addPlayer(e){
  playersRef.push({ board: createBoard(), shots: createBoard(), totalHits: 0, active: false });
  $('#currentPlayers').text(totalPlayers);
  $("button").addClass("hidden");
}

playersRef.on("child_added", function(snapshot) {
  if ($("button").hasClass("hidden") && !myID) { //count
    myID = snapshot.key();
    console.log("button shoudl be hidden. my id is: " + myID);
  }
snapshot.key()
})


function countShips() {
  console.log("Count ships has been fired because there are two players.");
}
// var playerTurn = function() {
//   the players are unique bc they each have a unique id generated by push()
//   var turn = player1;
//   console.log();
// }
//The existence of playerTurn means the game is on. Playerturn doesnt exists as a an obj in firebase until player are equal to two. Playerturn is nullified upon a win or cats game.
